name: wayfinder_geocoding_client
description: Serverpod client for the Wayfinder geocoding server.
publish_to: none

environment:
  sdk: '^3.8.0'

resolution: workspace

dependencies:
  serverpod_client: 3.4.8
