/// Built-in marker icon category keys (mirrored on the server).
abstract final class MarkerIconCategories {
  static const general = 'general';
  static const places = 'places';
  static const transportation = 'transportation';
  static const peopleAnimals = 'people_animals';
  static const infrastructure = 'infrastructure';
  static const military = 'military';
  static const emergency = 'emergency';
  static const shelterPreparedness = 'shelter_preparedness';
  static const recreation = 'recreation';
  static const agriculture = 'agriculture';
  static const custom = 'custom';

  static const defaultCategory = custom;

  static const orderedKeys = [
    general,
    places,
    transportation,
    peopleAnimals,
    infrastructure,
    emergency,
    military,
    shelterPreparedness,
    recreation,
    agriculture,
    custom,
  ];
}

/// Default category assignments for built-in marker icon keys.
const markerIconCategoryByKey = <String, String>{
  'place': MarkerIconCategories.general,
  'flag': MarkerIconCategories.general,
  'star': MarkerIconCategories.general,
  'favorite': MarkerIconCategories.general,
  'warning': MarkerIconCategories.general,
  'info': MarkerIconCategories.general,
  'geocache': MarkerIconCategories.general,
  'my_location': MarkerIconCategories.general,
  'camera': MarkerIconCategories.general,
  'home': MarkerIconCategories.places,
  'house': MarkerIconCategories.places,
  'apartment': MarkerIconCategories.places,
  'work': MarkerIconCategories.places,
  'school': MarkerIconCategories.places,
  'store': MarkerIconCategories.places,
  'restaurant': MarkerIconCategories.places,
  'local_cafe': MarkerIconCategories.places,
  'hotel': MarkerIconCategories.places,
  'church': MarkerIconCategories.places,
  'mosque': MarkerIconCategories.places,
  'community_center': MarkerIconCategories.places,
  'monument': MarkerIconCategories.places,
  'park': MarkerIconCategories.places,
  'police_department': MarkerIconCategories.places,
  'post_office': MarkerIconCategories.places,
  'courthouse': MarkerIconCategories.places,
  'library': MarkerIconCategories.places,
  'bank': MarkerIconCategories.places,
  'cemetery': MarkerIconCategories.places,
  'college': MarkerIconCategories.places,
  'fire_station': MarkerIconCategories.places,
  'prison': MarkerIconCategories.places,
  'jail': MarkerIconCategories.places,
  'airstrip': MarkerIconCategories.places,
  'port': MarkerIconCategories.places,
  'dock': MarkerIconCategories.places,
  'rally': MarkerIconCategories.places,
  'staging': MarkerIconCategories.places,
  'workshop': MarkerIconCategories.places,
  'retreat': MarkerIconCategories.places,
  'ham_shack': MarkerIconCategories.places,
  'security_post': MarkerIconCategories.places,
  'safe_room': MarkerIconCategories.places,
  'directions_car': MarkerIconCategories.transportation,
  'directions_bike': MarkerIconCategories.transportation,
  'hiking': MarkerIconCategories.transportation,
  'on_foot': MarkerIconCategories.transportation,
  'horse': MarkerIconCategories.transportation,
  'motorcycle': MarkerIconCategories.transportation,
  'atv': MarkerIconCategories.transportation,
  'truck': MarkerIconCategories.transportation,
  'bus': MarkerIconCategories.transportation,
  'rv': MarkerIconCategories.transportation,
  'train': MarkerIconCategories.transportation,
  'boat': MarkerIconCategories.transportation,
  'ferry': MarkerIconCategories.transportation,
  'yacht': MarkerIconCategories.transportation,
  'sailboat': MarkerIconCategories.transportation,
  'river_boat': MarkerIconCategories.transportation,
  'canoe': MarkerIconCategories.transportation,
  'helicopter': MarkerIconCategories.transportation,
  'glider': MarkerIconCategories.transportation,
  'balloon': MarkerIconCategories.transportation,
  'farm_vehicle': MarkerIconCategories.transportation,
  'evac_route': MarkerIconCategories.transportation,
  'pets': MarkerIconCategories.peopleAnimals,
  'man': MarkerIconCategories.peopleAnimals,
  'woman': MarkerIconCategories.peopleAnimals,
  'boy': MarkerIconCategories.peopleAnimals,
  'girl': MarkerIconCategories.peopleAnimals,
  'cat': MarkerIconCategories.peopleAnimals,
  'dog': MarkerIconCategories.peopleAnimals,
  'livestock': MarkerIconCategories.peopleAnimals,
  'cell_tower': MarkerIconCategories.infrastructure,
  'weather_station': MarkerIconCategories.infrastructure,
  'radio_repeater': MarkerIconCategories.infrastructure,
  'water': MarkerIconCategories.infrastructure,
  'fuel': MarkerIconCategories.infrastructure,
  'gate': MarkerIconCategories.infrastructure,
  'crossing': MarkerIconCategories.infrastructure,
  'lookout': MarkerIconCategories.infrastructure,
  'power': MarkerIconCategories.infrastructure,
  'power_plant': MarkerIconCategories.infrastructure,
  'nuclear_power_plant': MarkerIconCategories.infrastructure,
  'wind_turbine': MarkerIconCategories.infrastructure,
  'fuel_depot': MarkerIconCategories.infrastructure,
  'water_well': MarkerIconCategories.infrastructure,
  'cistern': MarkerIconCategories.infrastructure,
  'dead_zone': MarkerIconCategories.infrastructure,
  'hazard': MarkerIconCategories.infrastructure,
  'restricted': MarkerIconCategories.infrastructure,
  'defense': MarkerIconCategories.military,
  'army_base': MarkerIconCategories.military,
  'navy_base': MarkerIconCategories.military,
  'marine_corps_base': MarkerIconCategories.military,
  'air_force_base': MarkerIconCategories.military,
  'space_force_base': MarkerIconCategories.military,
  'coast_guard_base': MarkerIconCategories.military,
  'armory': MarkerIconCategories.military,
  'nuclear_weapons_facility': MarkerIconCategories.military,
  'ammo_cache': MarkerIconCategories.military,
  'local_hospital': MarkerIconCategories.emergency,
  'ambulance': MarkerIconCategories.emergency,
  'fire_truck': MarkerIconCategories.emergency,
  'medical_cache': MarkerIconCategories.emergency,
  'pharmacy': MarkerIconCategories.emergency,
  'decon_station': MarkerIconCategories.emergency,
  'supply_cache': MarkerIconCategories.shelterPreparedness,
  'camp': MarkerIconCategories.shelterPreparedness,
  'fallout_shelter': MarkerIconCategories.shelterPreparedness,
  'storm_shelter': MarkerIconCategories.shelterPreparedness,
  'bunker': MarkerIconCategories.shelterPreparedness,
  'root_cellar': MarkerIconCategories.shelterPreparedness,
  'firewood_cache': MarkerIconCategories.shelterPreparedness,
  'grain_silo': MarkerIconCategories.shelterPreparedness,
  'hunting': MarkerIconCategories.recreation,
  'fishing': MarkerIconCategories.recreation,
  'foraging': MarkerIconCategories.recreation,
  'cave': MarkerIconCategories.shelterPreparedness,
  'garden': MarkerIconCategories.agriculture,
  'greenhouse': MarkerIconCategories.agriculture,
};

String markerIconCategoryForKey(String key, {String? override}) {
  if (override != null && override.isNotEmpty) {
    return override;
  }
  return markerIconCategoryByKey[key] ?? MarkerIconCategories.defaultCategory;
}
