import 'dart:math';

import 'package:flutter/foundation.dart';

/// Radio-friendly single-word nouns for card-of-the-day code words.
///
/// Stored uppercase. Safe to reuse across different days/cards; callers must
/// exclude nouns already used on the *same* card.
const List<String> cardOfTheDayNouns = [
  'ACORN',
  'ANCHOR',
  'ANVIL',
  'APPLE',
  'ARROW',
  'ASPEN',
  'BADGER',
  'BANDIT',
  'BANNER',
  'BARLEY',
  'BEACON',
  'BEAVER',
  'BIRCH',
  'BLAZE',
  'BOLT',
  'BOULDER',
  'BRAVO',
  'BRIDGE',
  'BRONZE',
  'BUCKET',
  'BUFFALO',
  'CABLE',
  'CACTUS',
  'CANYON',
  'CARGO',
  'CEDAR',
  'CHAIN',
  'CHALK',
  'CIPHER',
  'CITRUS',
  'CLAW',
  'COBALT',
  'COBRA',
  'COPPER',
  'CORAL',
  'COYOTE',
  'CRANE',
  'CREEK',
  'CROWN',
  'DAGGER',
  'DELTA',
  'DIAMOND',
  'DRIFTER',
  'EAGLE',
  'ECHO',
  'EMBER',
  'FALCON',
  'FENCE',
  'FERRET',
  'FIELD',
  'FLAME',
  'FLINT',
  'FOREST',
  'FORGE',
  'FOX',
  'FROST',
  'GHOST',
  'GLACIER',
  'GLIDER',
  'GRANITE',
  'GRIZZLY',
  'HAMMER',
  'HARVEST',
  'HAWK',
  'HAZEL',
  'HELIX',
  'HERON',
  'HICKORY',
  'HORNET',
  'HUNTER',
  'ICEBERG',
  'IVY',
  'JACKAL',
  'JASPER',
  'JUNIPER',
  'KESTREL',
  'KEYSTONE',
  'LADDER',
  'LARK',
  'LEDGER',
  'LINEN',
  'LIZARD',
  'LOCUST',
  'LOTUS',
  'MAGNET',
  'MAPLE',
  'MARBLE',
  'MEADOW',
  'MERCURY',
  'MIRROR',
  'MOON',
  'MOSS',
  'NEEDLE',
  'NICKEL',
  'NIGHT',
  'OAK',
  'OCEAN',
  'ONYX',
  'ORBIT',
  'OSPREY',
  'OTTER',
  'OXBOW',
  'OYSTER',
  'PANTHER',
  'PEBBLE',
  'PHOENIX',
  'PINE',
  'PIONEER',
  'PISTON',
  'PLAINS',
  'PLUME',
  'POLE',
  'PRAIRIE',
  'PUMICE',
  'PYTHON',
  'QUARTZ',
  'QUILL',
  'RABBIT',
  'RADAR',
  'RAVEN',
  'RIDGE',
  'RIVER',
  'ROCKET',
  'SABER',
  'SALMON',
  'SAND',
  'SCORPION',
  'SHADOW',
  'SILVER',
  'SPARROW',
  'SPIDER',
  'SPIRE',
  'SQUALL',
  'STAG',
  'STONE',
  'STORM',
  'SUMMIT',
  'TALON',
  'THUNDER',
  'TIGER',
  'TIMBER',
  'TORCH',
  'TOWER',
  'TRAIL',
  'TUNDRA',
  'TURRET',
  'VALLEY',
  'VIPER',
  'VORTEX',
  'WALNUT',
  'WASP',
  'WILLOW',
  'WOLF',
  'WREN',
  'ZEPHYR',
];

/// Picks a noun not already present in [usedOnCard] (case-insensitive).
///
/// Returns `null` when every noun in [cardOfTheDayNouns] is already used.
String? pickRandomCardOfTheDayNoun({
  required Iterable<String> usedOnCard,
  Random? random,
}) {
  return pickRandomCardOfTheDayNounForTest(
    usedOnCard: usedOnCard,
    random: random ?? Random.secure(),
  );
}

@visibleForTesting
String? pickRandomCardOfTheDayNounForTest({
  required Iterable<String> usedOnCard,
  required Random random,
  List<String> nouns = cardOfTheDayNouns,
}) {
  final used = <String>{
    for (final word in usedOnCard)
      if (word.trim().isNotEmpty) word.trim().toUpperCase(),
  };
  final available = [
    for (final noun in nouns)
      if (!used.contains(noun.toUpperCase())) noun.toUpperCase(),
  ];
  if (available.isEmpty) {
    return null;
  }
  return available[random.nextInt(available.length)];
}
