#!/usr/bin/env node
/**
 * Measure marker SVG artwork bounds and generate per-icon fit scales for the
 * Flutter client. Icons with smaller artwork relative to their canvas (or
 * non-square canvases displayed in the circular map slot) get a larger scale.
 *
 * Usage:
 *   node scripts/compute_marker_glyph_scales.mjs [--render-width 256] [--target-fill 0.88]
 *
 * Requires: npm install --prefix scripts, npx @resvg/resvg-js-cli
 */

import { execFileSync } from 'node:child_process';
import {
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, '..');
const markersDir = join(repoRoot, 'wayfinder_flutter/assets/markers');
const outputPath = join(
  repoRoot,
  'wayfinder_flutter/lib/features/markers/models/marker_icon_asset_fit_scales.g.dart',
);
const pinFileName = 'marker_pin.svg';

const args = process.argv.slice(2);
const renderWidthIndex = args.indexOf('--render-width');
const targetFillIndex = args.indexOf('--target-fill');
const renderWidth = renderWidthIndex === -1
  ? 256
  : Number.parseInt(args[renderWidthIndex + 1] ?? '256', 10);
const targetFill = targetFillIndex === -1
  ? 0.88
  : Number.parseFloat(args[targetFillIndex + 1] ?? '0.88');

const scaleMin = 0.5;
const scaleMax = 5.0;

function run(command, commandArgs) {
  execFileSync(command, commandArgs, { stdio: 'pipe' });
}

function rasterizeSvg(inputSvgPath, outputPngPath) {
  run('npx', [
    '--yes',
    '@resvg/resvg-js-cli',
    '--fit-width',
    String(renderWidth),
    '--no-system-font',
    inputSvgPath,
    outputPngPath,
  ]);
}

function alphaBounds(pngBuffer) {
  const png = PNG.sync.read(pngBuffer);
  const { width, height, data } = png;
  let minX = width;
  let minY = height;
  let maxX = -1;
  let maxY = -1;

  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const alpha = data[(y * width + x) * 4 + 3];
      if (alpha > 8) {
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
      }
    }
  }

  if (maxX < minX || maxY < minY) {
    return null;
  }

  return {
    width: maxX - minX + 1,
    height: maxY - minY + 1,
    renderWidth: width,
    renderHeight: height,
  };
}

function clampScale(scale) {
  return Math.min(scaleMax, Math.max(scaleMin, scale));
}

function roundScale(scale) {
  return Math.round(scale * 1000) / 1000;
}

const tempDir = mkdtempSync(join(tmpdir(), 'marker-glyph-scales-'));
const results = [];

try {
  for (const fileName of readdirSync(markersDir).filter((name) => name.endsWith('.svg')).sort()) {
    if (fileName === pinFileName) {
      continue;
    }

    const key = fileName.replace(/\.svg$/, '');
    const svgPath = join(markersDir, fileName);
    const pngPath = join(tempDir, `${key}.png`);
    rasterizeSvg(svgPath, pngPath);
    const bounds = alphaBounds(readFileSync(pngPath));
    if (!bounds) {
      console.warn(`skip ${fileName}: no visible pixels`);
      continue;
    }

    const visualExtent = Math.max(bounds.width, bounds.height);
    const relativeExtent = visualExtent / bounds.renderWidth;
    const scale = clampScale(targetFill / relativeExtent);
    results.push({ key, scale: roundScale(scale), relativeExtent });
  }
} finally {
  rmSync(tempDir, { recursive: true, force: true });
}

results.sort((a, b) => a.key.localeCompare(b.key));

const lines = results.map(
  ({ key, scale }) => `  '${key}': ${scale.toFixed(3)},`,
);

const output = `// GENERATED by scripts/compute_marker_glyph_scales.mjs
// ignore_for_file: constant_identifier_names

/// Per-icon fit scales derived from rendered artwork bounds in bundled SVGs.
///
/// Combined with [MarkerIconOption.glyphScale] when drawing [MarkerIconGlyph].
const Map<String, double> markerIconAssetFitScales = {
${lines.join('\n')}
};

/// Default fit scale for icons without bundled metrics (custom server SVGs).
const double markerIconDefaultAssetFitScale = 1.0;
`;

writeFileSync(outputPath, output);

console.log(`Wrote ${results.length} fit scales to ${outputPath}`);
for (const { key, scale, relativeExtent } of results) {
  if (scale >= 1.35 || scale <= 0.75) {
    console.log(`  ${key}: ${scale} (extent ${(relativeExtent * 100).toFixed(1)}%)`);
  }
}
