graphhopper:
  datareader.file: ""
  graph.location: graph-cache

  profiles:
    - name: car
      custom_model_files: [car.json]
    - name: foot
      custom_model_files: [foot.json, foot_elevation.json]
    - name: bike
      custom_model_files: [bike.json, bike_elevation.json]

  profiles_ch:
    - profile: car

  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 127.0.0.1
      max_request_header_size: 50k
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990
      bind_host: 127.0.0.1

logging:
  appenders:
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
